dist: trusty
language: node_js
notifications:
  email: false
node_js: lts/*
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - npm run format:check
        - npm run lint
        - npm run test:ci
        - npm run coverage:check
        - npm run build
        - npm run build:ivy
        - npm run test:report
      deploy:
        provider: script
        script: npm run semantic-release
        skip_cleanup: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(master|next|channel-ivy)$
